# Generated by Django 5.2.17 on 2026-09-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Copy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, unique=True, verbose_name="Инвентарный номер"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies",
                        to="catalog.book",
                        verbose_name="Книга",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies",
                        to="inventory.branch",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экземпляр",
                "verbose_name_plural": "Экземпляры",
                "ordering": ["id"],
            },
        ),
    ]
