# Generated by Django 5.2.17 on 2026-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="shelf_location",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Место хранения"
            ),
        ),
    ]
