# Generated by Django 5.2.17 on 2026-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_copy_shelf_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="status",
            field=models.CharField(
                choices=[("available", "Доступен"), ("issued", "Выдан"), ("withdrawn", "Списан")],
                default="available",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
