# Generated by Django 5.2.17 on 2026-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
    ]
